name = "glimr_postgres"
version = "0.2.0"

description = "PostgreSQL driver for the Glimr web framework"
licences = ["MIT"]
repository = { type = "github", user = "glimr-org", repo = "postgres" }

[dependencies]
glimr = ">= 0.5.0 and < 0.6.0"
pog = ">= 4.0.0 and < 5.0.0"
gleam_stdlib = ">= 0.44.0 and < 0.67.1"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
